### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by Zachoeser** [wuspy/portal_calendar#20]
Hello! I am excited to say im on the last step of this project. Your instructions have been wonderful.  I have assembled my board in the 3d printed frame and am to the programming stage. I have successfully uploaded the config fille in IDE under both the void setup and void loop areas of the programming. However the screen never lights up or displays any information. This is my time with Arduino and i feel like i may be missing a step. I have done plenty of googleing but would  appreciate some help. Thank you!
![ide2](https://github.com/wuspy/portal_calendar/assets/120290498/01ac9d18-fa4c-4959-aa6c-b4efeb9d97ca)
![ide](https://github.com/wuspy/portal_calendar/assets/120290498/6993f958-411c-48c2-a097-f068d728d4d9)

**Comment by wuspy** [comment]
Hey! Correct me if I'm wrong but it looks like you just copied the config file into a new arduino project? That's not going to work on its own, you need the rest of the code from this repository. Download the whole repository with Code -> Download ZIP
![image](https://github.com/wuspy/portal_calendar/assets/10302670/bd04e5ff-5b1d-444e-95cb-4c82f4276266)
Extract it, then open portal_calendar.ino in Arduino IDE. Then click on config.h in the top bar and fill out your stuff there.

Also, your wifi name and password is visible in that first screenshot so you may want to delete it.

**Comment by Zachoeser** [comment]
Hey Jacob,
Thank you so much for the response. I somehow missed that step! I uploaded
everything and it is working perfectly! What a cool project you made, I
wonder how many people put it together. This is my first time doing any
project like this and it means alot to get a response. I look forward to
playing with it. Keep up the great work and have a good night!
