### ISSUE TITLE
Waveshare E-Paper Driver Board Rev2.3

### ISSUE THREAD

**Issue by YeahBob** [wuspy/portal_calendar#22]
Note: Waveshare has updated their e-paper driver board to Rev2.3.  This project is designed to work with Rev2.2. If you have the Rev2.3 board, you will need to solder a 47k resistor to the pads on the back of the board shown here:
![image](https://github.com/wuspy/portal_calendar/assets/156418969/aa8c3c8e-3d21-4a40-b1fc-04205de337fe)
Do not connect the PWR pin. This will ensure this board works with this project without the need to modify any files or pin assignments. More details can be found here:
https://www.waveshare.com/wiki/E-Paper_Driver_HAT
Hopefully this helps anyone who tries this project in the future! :D

**Comment by wuspy** [comment]
I didn't know they released a new revision, thanks for bringing this up. I'll try to get the code and documentation updated to handle it once I have one to test. I'd rather not make surface mount soldering required for this project.

**Comment by falkyoung** [comment]
I just encountered this and connected the `PWR`  pin to 3.3v. So my mapping is:

| e-Paper HAT   |     | ESP32 |
| ------------  | --- | ----- |
| VCC (Grey)    | <-> | 3.3v  |
| PWR (Red)     | <-> | 3.3v  |
| GND (Brown)   | <-> | GND   |
| DIN (Blue)    | <-> | D13   |
| CLK (Yellow)  | <-> | D14   |
| CS (Orange)   | <-> | D15   |
| DC (Green)    | <-> | D23   |
| RST (White)   | <-> | D33   |
| BUSY (Purple) | <-> | D27   |

![IMG_20240126_192859456 (1)](https://github.com/wuspy/portal_calendar/assets/83219076/1ad07c74-edaf-495e-8278-d356a066774c)

Seems to work so far. @wuspy Let me know if I can be of any assistance when it comes to updating docs/ code.

**Comment by wuspy** [comment]
@falkzeh I got one of the new driver boards and did some testing with it, and although wiring PWR straight to 3.3v works it uses far too much idle power in my testing. The new revision measured at Vin draws 430uA in deep sleep, while the old one draws just 12uA. That kind of parasitic power draw would kill AAA batteries in a few weeks. So it looks like I'll need to look into the changes waveshare made to their example code to see what they're doing, hopefully it's just a simple as switching PWR before a display refresh. Disconnecting PWR on the new driver board does drop it down to 12uA just like the old one.

My test setup involves just bridging a cheap multimeter across one of the battery contacts so it isn't the most accurate thing in the world, but I've tried it several times while swapping the driver board back and forth and so I'm fairly confident in these results.

**Comment by wuspy** [comment]
[This is the commit in waveshare's examples adding support for this board.](https://github.com/waveshareteam/e-Paper/commit/a550cc47fa320d2ae7d89d6028452ce01c11ef1d) Like I suspected they're just wiring it to a pin that's set high when the display is initialized, although they're never setting it low again which is strange. I'm doing something similar, wiring it to IO26 and setting it high in wakeup() and low and sleep() and it seems to work fine, power usage in sleep is the same as it was before. I'll do a bit more testing then update the code and documentation.

**Comment by wuspy** [comment]
Fixed in 11559a0
