### ISSUE TITLE
Stuck in Setup-Mode?

### ISSUE THREAD

**Issue by legrex** [wuspy/portal_calendar#24]
Hi,

thanks for your project, had a lot of fun printing, soldering and putting it all together. Just finished an hour ago and had it up and running with the Weather showing for the next 5 days. Then i wanted to see how the Forecast-Mode for just the current day looks and pressed reset and went back to the web-installer and configured it. So then i get the 

"Setup Complete

You can now close this page and unplug the calendar. If you want to change something later, plug in the calendar and press the RESET button on the back to enter setup mode again."-Message

But after that i'm lost. The Display still shows the QR-Code and Setup-Instructions. If i Power-Cycle it always goes back to this, issueing a new wifi-key. So i have no idea how to get to the Calendar-View again? Am i missing something, did i miss to read about a step?

Thank you again, 
sincerely,
Grex

**Comment by wuspy** [comment]
If it's going back to the welcome screen then that means one of these checks is failing
```cpp
bool ConfigurationClass::isConfigured()
{
    return !(
        getWifiSsid().isEmpty() ||
        getTimezoneName().isEmpty() ||
        getPrimaryNtpServer().isEmpty() ||
        getPrimaryTimezonedServer().isEmpty() ||
        (getWeatherEnabled() && (
            getOwmApiKey().isEmpty() ||
            getWeatherLocationLatitude() == 0.0 ||
            getWeatherLocationLongitude() == 0.0
        ))
    );
}
```
The setup app shouldn't let you continue if that's the case so there's probably a bug in the validation it's doing. Is your API key and location filled out on the weather page, and do they both turn green? If you disable the weather, does it work?

**Comment by legrex** [comment]
That was the first i tried, disabling weather but with the same outcome. Also all Fields in this check are filled out and API-Key and Location turning green. Maybe i "destroyed" a solder joint at the end and the display is just not updating? Are IO13-15 for the Control of the e-ink-display?

Edit: Ah, but i still see the PortalCalendar-Wifi, i guess that should be shut down if it would have left the Setup-Mode?

**Comment by wuspy** [comment]
Oh I think I misread your message, I thought it was going back to the welcome screen telling you to connect to power, but it's actually just staying on the QR code screen. If that's the case then it must think it's still connected to power, which could only happen if IO19 is pulled high. Do you have some soldering bridging that to Vin maybe?

And yes IO13-15 are used for controlling the display, so those need to be well connected and not shorted together. Is the display going through a refresh cycle (alternating black/white) when you press reset or does nothing happen at all?

![Screenshot from 2024-02-03 17-14-09](https://github.com/wuspy/portal_calendar/assets/10302670/04bffa70-eb27-4666-827b-4bb27e6ebf73)

**Comment by legrex** [comment]
You're totally right. Vin was correctly soldered, but i did not cut the something to long wire down and as i was assembling the Cover it must have shortened IO19. I cut it now and it's working. Thank you so much!
