### ISSUE TITLE
EzSBC website instability

### ISSUE THREAD

**Issue by Patxi080** [wuspy/portal_calendar#3]
Hi, I only want to tell you that the ESP32 link is broken.

**Comment by wuspy** [comment]
The EzSBC website? Yeah, I noticed a couple days ago that it was pretty unreliable. I'm still able to access it if I catch it at the right time though.

Even though there's nothing I can really do about this, I'll keep this issue up until they (hopefully) fix it.

**Comment by Patxi080** [comment]
Could you tell me what exact ESP32 model you used? I'm asking because it says this in the readme: "This will run on any ESP32, but this particular board is perfect for alkaline battery power due to its efficient voltage regulator and flexible input voltage. If you use a different board, you will need to modify the case and come up with your own power solution." Thx.

**Comment by wuspy** [comment]
It's designed & made by EzSBC and and I don't currently know of any resellers.

They do have a store on Tindie though https://www.tindie.com/products/ddebeer/esp32-dev-board-wifibluetooth/

**Comment by Patxi080** [comment]
And you used this model because the batteries last longer, right?

**Comment by wuspy** [comment]
Pretty much, I couldn't find any other breakout board that came even close to the sleep current that one has. Most of them are designed for LiPo power where sleep current doesn't really matter because you'll be recharging it regularly anyway.

**Comment by wuspy** [comment]
Added tindie link to readme in case the site goes down again in the future 01aad1e709e975ea14884324948a4c14a6f3a06f
