### ISSUE TITLE
Avoiding Hardcoding WiFi Credentials

### ISSUE THREAD

**Issue by LordNed** [wuspy/portal_calendar#7]
Neat project. I'd like to give one as a gift but teaching friends how to compile and flash an ESP32 might be a bit too much of a gift. I was looking at potentially forking and integrating a wifi manager where, if wifi connection fails, it boots up into access point mode so you can connect to it via your phone and enter wifi credentials, and then have them saved on the device.

Looking around it looks like there's a package for the ESP32 by user Tzapu - https://github.com/tzapu/WiFiManager. Is this something you're interested in taking a pull request to add? If so, do you have thoughts on how you would want it implemented. I can make an effort to implement it that way to make it easier to take back as a PR.

My initial thoughts were to just set up a new set of defines in the header, instead of:

`#define WIFI_NAME "your wifi name here"
#define WIFI_PASS "your wifi password here"`

Have something like
```
#define USE_ACCESS_POINT_CONFIG 1
#if USE_ACCESS_POINT_CONFIG
// IP Address the device will create a webserver on to config
#define WIFI_ACCESSPOINT_NAME "Aperture Labs Non-Sentient Devices"
#define WIFI_ACCESSPOINT_PASSCODE ""
#else
#define WIFI_NAME "your wifi name here"
#define WIFI_PASS "your wifi pass here"
```

And then whatever changes need to be made to the cpp files to branch them based on #if USE_ACCESS_POINT_CONFIG or not. I won't be able to tinker around with the code for a while until an ESP32 gets here but skimming both portal_calender.ino and the examples for the WiFiManager it looks relatively straightforward. The WiFi Manager will block the init loop until successfully connected to a real wifi connection, though it would be handy if we could display a string with instructions (connect to access point, navigate to any webpage on device, get redirected to config page, enter credentials, etc.)

**Comment by wuspy** [comment]
I think this would be a great feature and it's something I wanted to do originally. Ideally, all settings would be configurable from the web UI, then config.h wouldn't even be necessary and there would never be a need for an end user to re-flash.

However, it's not ideal to have it running an AP on battery power, and it's definitely not a good idea to have it automatically fall-back to the AP in case the wifi connection fails since it could potentially be running it on battery power for hours before the user notices. Luckily this board does have a way to detect if its running on USB power, so we could make a workflow where it instructs them to plug the device in to begin setup, then goes to sleep, waking up every second or two to check if it's on USB power yet, then starts the AP and displays the SSID and password on the display, maybe even with a [QR code](https://github.com/nayuki/QR-Code-generator/tree/master/cpp) if we want to be fancy.

```cpp
/**
 * On the EzSBC breakout board, pin 19 is connected to Vusb through an LED and a 1k resistor, meaning it is pulled
 * high if the board is on USB power.
 */
bool isOnUsbPower()
{
    pinMode(19, INPUT_PULLDOWN);
    return digitalRead(19) == HIGH;
}
```

I haven't taken current measurements of it in AP mode so I could be overestimating how much of a problem this is, and spending 10 minutes in AP mode while the user completes the setup might not be a big deal. However it's also possible that they could put in the batteries, and then just not touch it for a couple days without realizing that its rapidly draining them down.

So yeah, I'm definitely open to a pull request if you want to take a shot at this.

**Comment by LordNed** [comment]
Still no ESP32 but started poking around the code tonight. I didn't want to make a fork with a bunch of untested checkins, but wanted to run proposed code/flow changes by you;

1) startWifi/stopWifi route through the wifiManager now. the WiFiManager is told to not automatically make an AP when attempting an autoconnect, so it should attempt to connect for 10s, then fail and shut down wifi.

```
void stopWifi()
{
    if (WiFi.getMode() != WIFI_OFF) {
        DEBUG_PRINT("Stopping WiFi");
        unsigned long start = millis();
        wifiManager.disconnect()
        
        // Disable the WiFi hardware as well for power preservation.
        WiFi.mode(WIFI_OFF);
        DEBUG_PRINT("WiFi shutdown took %lums", millis() - start);
    }
}

bool startWifi()
{
  // Ensure the device is in Station Mode
  WiFi.mode(WIFI_STA);

  // If we're already connected, don't bother trying to connect again
  if(wifiManager.getLastConxResult() == WL_CONNECTED) {
    return true;
  }

  DEBUG_PRINT("Starting WiFi");
  unsigned long start = millis();
  
  // If we're not already connected, attempt to connect. By default WiFiManager will automatically
  // try to start an Access Point if connection fails (so you can connect to WiFiManager and configure)
  // but we suppress that behavior, so that we can display some info to the user.
  wifiManager.setEnableConfigPortal(false);
  wifiManager.setWiFiAutoReconnect(false); 
  wifiManager.setConnectTimeout(10); // Attempt to connect for ten seconds, then fail.

  // If there's no credentails to try and connect with, don't bother with the connection attempt.
  bool result = wifiManager.getWifiIsSaved();
  if(!result) {
    DEBUG_PRINT("No WiFi Credentials Saved, moving user to AP Setup Flow");

    // We call stopWiFi to clean up and shut down WiFi as much as possible
    stopWiFi();
    return false;
  }

  // If they do have credentials saved, attempt a connection.
  result = wifiManager.autoconnect();
  if(!result) {
    DEBUG_PRINT("WiFi connection failed after %lums, moving user to AP Setup Flow", millis() - start);

    stopWiFi();
    return false;
  }

  // If we got this far then they managed to connect to WiFi!
  DEBUG_PRINT("WiFi connection succeeded, took %lums", millis() - start);
  return true;
}
```

In setup() we now need to attempt to start the wifi before anything else like TIME_ZONE syncing, with a new error message prompting the user to plug into USB power. It wasn't clear to me from your code snippet if that was a function in an ESP32 library or not.
```
... existing debug logging code...
    // If we're rebooting because we ran out of power, print an error
    // (and this function never returns, the rest of setup is not run)
    if (esp_reset_reason() == ESP_RST_BROWNOUT) {
        errorBrownout();
    }

    // Attempt to connect to the WiFi. If connection fails then either credentials are wrong,
    // it's never been set up, or it's out of range. 
    bool bConnectedWiFi = startWiFi();

    if(!bConnectedWiFi)
    {
        // We failed to connect to the WiFi. We're going to ask the user to plug into USB power
        // instead of running the AP without them realizing it.
        if(!isOnUsbPower())
        {
            // If they're not currently on USB power, we will print an error message
            // asking them to plug in via USB, then restart. This function will never
            // return (enters deep sleep).
            errorNotOnUSBPowerToStartAP();
        }

        // If we are on usb power, we're going to start an Access Point that the user
        // can connect to with their phone to configure this display. This will print
        // some info to the screen
        doDeviceConfigurationFlow();
    }
```

doDeviceConfigurationFlow will start the Access Point. It took a while of digging around but it looks like the way WiFi QR codes work is just a pre-made pattern of text as the data for the QR Code (untested):
`WIFI:S:<SSID>;T:<WEP|WPA|blank>;P:<PASSWORD>;H:<true|false|blank>;;`
(H being hidden SSID I think). And the trailing two ";;" are important apparently.

I suspect in practice we'll want an actual QR Code drawing routine instead of encoding it into text - I have no idea what this will look like on an actual device. Also too bad the QR Code library doesn't support image overlays, could put a little Aperture Logo in the center of the QR code :)

```
void doDeviceConfigurationFlow()
{
    // To configure the device, the ESP32 will create an Access Point with a username/password.
    // The user will then connect to it via their phone, setup the access to the real WiFi
    // and then the ESP32 will close the Access Point and attempt to connect to the user-specified one.
    
    // We want to inform the user how to configure their Aperture Science Non-Sentient Device,
    // so we will take advantage of the screen to display some info + a QR Code to scan with the phone.
    // We can't use the standard error(...) function as that will enter deep sleep and prevent us from
    // ever starting the webportal.
    DEBUG_PRINT("Starting Device Configuration Flow");
    unsigned long start = millis();

    // ToDo: Find out if the ESP is WPA2 or WEP when in AP mode
    // To generate a QR Code that helps auto-connect your phone to a WiFi network, the
    // QR Code needs to have the following pattern, where H: means "Hidden" and is optional.
    // The trailing ";;" is important. Side note: This could probably be rewritten to cause
    // less heap fragmentation, since this info is the hard-coded Device AP, not user AP.
    // WIFI:S:<SSID>;T:<WEP|WPA|blank>;P:<PASSWORD>;H:<true|false|blank>;;
    String QRCodeData = String("WIFI:S:") + WIFI_AP_NAME + String(";T:WPA;P:") + WIFI_AP_PASSWORD + String(";H:false;;");

    // Now that we have the data as a string, we will generate a qr code.
    qrcodegen::QrCode qrCode = qrcodegen::QrCode::EncodeText(*QRCodeData, QrCode::Ecc::MEDIUM);

    // Finally, we refresh the display to show this information to the user. We could probably write a native QR Code drawing
    // routine for the display... or we could encode the QR Code as text and re-use the existing routine for displaying text. :)
    // (this is definitely not great for heap fragmentation, but also there's like 160kb of it...)
    String qrCodeAsString;
    int border = 4;
    for(int y = -border; y < qrCode.getSize() + border; y++)
    {
        for(int x  = - border; x < qrCode.getSize() + border; x++)
        {
          qrCodeAsString += qrCode.getModule(x, y) ? "##" : "  ";
        }
        qrCodeAsString += "\n";
    }


    std::initializer_list<String> userText = 
    {
      "Welcome to your Aperture Science Non-Sentient Device",
      "Please configure your device by using another WiFi",
      "capable Device (such as your phone) and connecting",
      "to the WiFi Network:",
      "SSID: \""WIFI_AP_NAME"\"",
      "Password: \""WIFI_AP_PASSWORD"\"",

      "Alternatively, you can scan the QR Code below to",
      "automatically be connected to \""WIFI_AP_NAME"\".",
      "",
      "",
      qrCodeAsString
    };

    // Draw our QR Code + User Prompt to Display, reusing the routine for displaying an error.
    const bool bWillRetry = false;
    display.error(userText, bWillRetry);

    // The startConfigPortal will block until the user confirms information.
    wifiManager.setConfigPortalBlocking(true);
    wifiManager.startConfigPortal(WIFI_AP_NAME, WIFI_AP_PASSWORD);
}
```

The hard-coded #if WEATHER won't work with dynamic webpage-based configuration. Do you want to gate these behind a `RTC_DATA_ATTR bool` property and do them dynamically? It isn't clear if there are any downsides to always including all the #ifdef'd functionality (weather, timezone, etc) (such as needing a third party library or not enough ROM space to have them all enabled, etc.)


I don't know if the WiFiManager webpage gives us enough controls or not, but would be neat if you could program someone's birthday in and have it do a full-screen Portal Birthday Cake drawing on the day, but probably beyond what I'm willing to do. :)
